version: '2.1'

services:
  bruna-danilo-testers-app:
    image: bruna-danilo-testers-app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js